# ENVIRONMENT VARIABLES ========================================================

# History
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000

# Set default editor to Vim
EDITOR=/usr/bin/vim
VISUAL=/usr/bin/vim


# OPTIONS ======================================================================

setopt autocd extendedglob nomatch
set -o vi

# Make v key open editor in zle command mode (kinda like with shell's vi-mode)
autoload edit-command-line
zle -N edit-command-line
bindkey -M vicmd v edit-command-line

# Completion
# The completion doesn't want to work on the mac and I can't be asked to fix it
if [ $(uname -s) = "Linux" ]
then
	# The following lines were added by compinstall
	zstyle :compinstall filename '/home/admin/.zshrc'

	autoload -Uz compinit
	compinit
	# End of lines added by compinstall
fi

# Zsh settings
# make completion be case-insensitive
zstyle ':completion:*' matcher-list '' 'm:{a-z}={A-Z}' '+m:{A-Z}={a-z}'
#  zstyle defines lookup styles for zsh.
#  These are context-related and change the behaviour of shell
#  functions, that look, which styles are defined.
#  The completion system uses styles for its completion behaviour and
#  output.
#  The context for the compsys is ':completion:', ':completion:*'
#  matches all other fields of the zstyle commands, for you can get
#  awfully specific using those…
#  The 'matcher-list' is a set of style-rules applied to all completers
#  whenever a completion takes place. 'm:{a-z}={A-Z}' matches lowercase
#  letters to their uppercase counterparts, when the lowercase letters
#  don't return a match. '+m:{A-Z}={a-z}' does the same in the other
#  direction, the '+' adds this rule to the previous instead of
#  overwriting it.


# SOURCE SCRIPTS ===============================================================

source "$HOME/.zrc/aliases"
source "$HOME/.zrc/prompt"

source "$HOME/.scripts/cdsearch"
source "$HOME/.scripts/vsearch"

source "$HOME/.bookmarks/bmark-cd"
source "$HOME/.bookmarks/bmark-cd_vifm"
