#!/bin/bash

# Query filesystem with fd to compose playlist for mpv.
#
#  fdPlay [-f] [-r] ...
#
# [-f]	 use fzf as another filter (fzf -m)
# [-r]   randomize using sort -R (not strictly unix, but meh)
# $@     args to fd
#
# Note that expanding with $@ means you may pass flags and even other
# pipe-segments here:
#
#    fdPlay 'regex'
#    fdPlay -p 'folder\/regex' -e mp4
#    fdPlay -H | sort -h
#
# DEPENDENCIES: mpvPlay

[ "$1" = "-f" ] && { fzf=" | fzf -m"; shift 1; }
[ "$1" = "-r" ] && { randomize=" | sort -R"; shift 1; }

eval "fd -pt f -0 $@ " $fzf " | xargs -0 -I % realpath \"./%\"" $randomize " | mpvPlay"
