#!/bin/sh

# Query the filesystem using fd and open matched files in sxiv.
#
#     fdShow [-r] ...
#
# Note the $@ expansion means, you may pass flags and other pipelined commands
# to this script.
#
# DEPENDENCIES: sanitize

[ "$1" = "-r" ] && { randomize="-R"; shift 1; }

fd -pt f "$@" | sort $randomize | sxiv -qabo -
