#!/bin/bash

# Playback playlist using mpv from stdin.
# stdin	    entries of the playlist

random="$(head -c 100 </dev/urandom | cksum | cut -d' ' -f1)"
fname="/tmp/playlist-$PPID-$random"
echo "Playlist File: $fname"

xargs -0 >> $fname

mpv --input-media-keys=no --playlist $fname

rm $fname
