#!/bin/dash

function recurr {
   $@

   while [ $? -ne 0 ]
   do
      echo "command: $1 exited with code 1 [ERROR]"
      echo "waiting 5 seconds for User Interrupt until recursion"
      sleep 5s
   done

}
  
recurr $@
