#!/bin/sh

# $1	where to start from
# $2	show hidden files if not ""
# $3	prompt

# test: -z  true if string has length 0 ("")
# grep: -v  invert match

[ -z "$1" ] && target="$(realpath .)" || target="$1"
[ -z "$2" ] && show_hidden=""         || show_hidden="-a"
prompt="$3"


while true; do

   [ -z "$prompt" ] && actual_prompt="$target" || actual_prompt="$prompt"

   selection="$(ls -1 $show_hidden "$target" | grep -v '^\.$' | dmenu -i -p "$actual_prompt" -l 25)"


   # dmenu escaped or cancelled
   exit_code="$?"
   [ "$exit_code" -ne 0 ] && exit $exit_code


   # choose new valid path
   if [ "$(dirname "$selection")" = "/" ]; then
      new_target="$selection"
   else
      new_target="$(realpath "$target/$selection")"
   fi

   [ -e "$new_target" ] && target="$new_target"


   # file was selected
   if [ ! -d "$target" ]; then
      echo "$target"
      exit 0
   fi

done
