#!/bin/bash

# Query filesystem with fd to compose playlist for mpv.
#
#  fdPlay [-r] ...
#
# [-r]   randomize using sort -R (not strictly unix, but meh)
# $@     args to fd
#
# Note that expanding with $@ means you may pass flags and even other
# pipe-segments here:
#
#    fdPlay 'regex'
#    fdPlay -p 'folder\/regex' -e mp4
#    fdPlay -H | sort -h
#
# DEPENDENCIES: mpvPlay

[ "$1" = "-r" ]; { randomize=" | sort -R"; shift 1; }

eval "fd -0 -t f $@ | xargs -0 -I % realpath \"./%\"" $randomize " | mpvPlay"
