#!/bin/bash

# Query filesystem with fd to compose playlist for mpv.
#
# $@	args to fd
#
# Note that expanding with $@ means you may pass flags and even other
# pipe-segments here:
#
#    fdPlay 'regex'
#    fdPlay -p 'folder\/regex' -e mp4
#    fdPlay -H | sort -h

# xargs -d makes quotes be non-special characters, necessary for filenames,
# that may contain quotes

fname="playlist-$RANDOM"

fd -t f $@ | xargs -d "\n" -I % realpath "./%" >> $fname

mpv --playlist $fname

rm $fname
