#!/bin/bash

# Query filesystem with fd to compose playlist for mpv.
#
# $@	args to fd
#
# Note that expanding with $@ means you may pass flags and even other
# pipe-segments here:
#
#    fdPlay 'regex'
#    fdPlay -p 'folder\/regex' -e mp4
#    fdPlay -H | sort -h
#
# DEPENDENCIES: mpvPlay

# xargs -d makes quotes be non-special characters, necessary for filenames,
# that may contain quotes

fd -t f $@ | xargs -d "\n" -I % realpath "./%" | mpvPlay
