#!/bin/sh

# ln_opts -- handler for command line options in ln* utilities
#
# exit code   how many positional parameters were used, i.e. need to be shifted
# stdout      the flags as a string, for use with eval
#
#
# Use like this:
#
#     # Handle options to ln
#     flags="$(ln_opts "$@")"
#     flagc=$?
#     shift $flagc
#
#     eval ln "$flags" ...
#
#
# Options are handled with these caveats:
# 
#    Only options, that DON'T take any arguments, i.e. don't contain any unquoted
#    spaces are supported. Options like:
# 
#       -s, --symbolic
#       -f, --force
# 
#    should work fine. Note that this also means argument-options with '='
#    assignment do work:
# 
#       --target-directory=DIR
# 
#    This script hands off all error handling about the existence and types of
#    TARGETs to the ln command itself.

flagc=0
for parameter; do
   # ln flags start with '-'
   case "$parameter" in
      -*)   flags="$flags $parameter"; flagc=$((flagc + 1)) ;;
      *)    break ;;
   esac
done

echo "$flags"
exit $flagc
