#!/bin/sh

helptext="
lnp [options] TARGET DESTINATION
lnp [options] TARGET... DESTINATION

In the 1st form DESTINATION may be a file or a folder. A folder is denoted by a
trailing '/'.
In the 2nd form DESTINATION will be treated as a folder name regardless.

Only options, that DON'T take any arguments, i.e. don't contain any unquoted
spaces are supported. Options like:

   -s, --symbolic
   -f, --force

should work fine. Note that this also means argument-options with '='
assignment do work:

   --target-directory=DIR

Tthis script hands off all error handling about the existence and types of
TARGETs to the ln command itself.
"


function lastPositionalParameter () {
   for parameter; do true; done
   echo "$parameter"
}


# Handle arguments to ln

flagc=0
for parameter; do
   if [ "-" = "$(printf "$parameter" | head -c 1)" ]; then
      flags="$flags $parameter"
      flagc=$((flagc + 1))
   else
      break
   fi
done

shift $flagc

[ $# -lt 2 ] && { echo "$helptext"; exit 1; }


# Make destination directory

# DESTINATION is a target file
if [ $# -eq 2 ] && [ ! '/' = "$(printf "$2" | tail -c 1)" ]; then
   destination="$2"
   mkdir -p "$(dirname "$2")"

# DESTINATION is a directory
else
   destination="$(lastPositionalParameter "$@")"
   mkdir -p "$destination"
fi


# Make links

# Link all TARGETs
paramc=1
for parameter; do

   [ $paramc = $# ] && break

   eval ln "$flags" "$parameter" "$destination"
   paramc=$((paramc + 1))

done
