#!/bin/sh

helptext="
lns -- ln from stdin

USAGE:

   lns [-p] [options] DESTINATION

DESCRIPTION:

   Reads filenames from stdin and links them into DESTINATION

OPTIONS:

   -p    Create DESTINATION with mkdir -p if it doesn't exist.
         This option has to be in the first position!

   All other options are handed off to the ln command.

   Only options, that DON'T take any arguments, i.e. don't contain any unquoted
   spaces are supported. Options like:

      -s, --symbolic
      -f, --force

   should work fine. Note that this also means argument-options with '='
   assignment do work:

      --target-directory=DIR

   This script hands off all error handling about the existence and types of
   TARGETs to the ln command itself.

DEPENDENCIES:

   ln_opts -- handler for command line options in ln* utilities
"

function lastPositionalParameter () {
   for parameter; do true; done
   echo "$parameter"
}


# -p flag set?
[ "$1" = "-p" ] && { mkparent=1; shift 1; }

# Handle options to ln
flags="$(ln_opts "$@")"
flagc=$?
shift $flagc

[ $# -ne 1 ] && { echo "$helptext"; exit 1; }

[ $mkparent ] && mkdir -p "$1"

xargs -I % -- sh -c "eval ln \"$flags\" \"%\""
