#!/usr/bin/awk -f

# Compute output filenames
BEGIN {

   # Get user's home directory
   home = ENVIRON["HOME"]

}

# Ignore empty lines and lines not starting with alnum chars
/^$/            { next; }
!/^[a-zA-Z0-9]/ { next; }

# Bookmark operations
{
   # Split and trim input
   symbol = substr($0, 1, match($0, /[[:space:]]*\|/)-1)
   path   = substr($0, index($0, "|")+1)
   sub(/[[:space:]]*$/, "", symbol)
   gsub(/\$HOME/, home, path)

   # The printf statements
   printf "alias cd%s=\"cd \\\"%s\\\"\"\n",         symbol, path >> "bmark-cd"
   printf "alias cc%s=\"cd \\\"%s\\\"; vifm .\"\n", symbol, path >> "bmark-cd_vifm"
   printf "bmark! \"%s/\" %s\n",                    path, symbol >> "bmark-vifm"
}
