#!/bin/bash

# Playback playlist using mpv from stdin.
# stdin	    entries of the playlist

random="$(cat /dev/urandom | head -c 100 | cksum | cut -d' ' -f1)"
fname="/tmp/playlist-$PPID-$random"

echo "Playlist File: $fname"

while read -r l; do echo "$l" >> $fname; done

mpv --playlist $fname

rm $fname
