#!/bin/sh

# sanitize -- escape characters with special meaning on the shell
#
# USAGE:
#
#	 sanitize [arg [...]]
#
#     If no arguments are provided, sanitize expects input from stdin
#
#     Note, that:
#
#	 sanitize "hello" "you" "there"
#
#     yields:
#
#	 hello\ you\ there

escape () { sed -E 's/([[:space:]]|[[:blank:]]|[[:cntrl:]]|[[:punct:]])/\\\1/g'; }

[ $# -eq 0 ] && escape || echo "$@" | escape
