#!/bin/sh

# Randomize input without relying on -R flag of sort.
#
# DON'T USE THIS IF YOU CAN AVOID IT, IT'S NOTICABLY SLOWER THAN SIMPLY USING
# SORT -R!
#
# DEPENDENCIES:
#     random   -- create random numbers in a POSIX safe way

# Not using xargs, because then the expansion would only be evaluated once

if [ $# -ne 0 -a "$1" != "-" ]
then cat "$@" | while read -r l; do echo "$(random 10)$l"; done | sort | cut -b 11-
else            while read -r l; do echo "$(random 10)$l"; done | sort | cut -b 11-
fi
