#!/bin/sh

# Randomize input without relying on -R flag of sort.
#
# DON'T USE THIS IF YOU CAN AVOID IT, IT'S NOTICABLY SLOWER THAN SIMPLY USING
# SORT -R!
#
# DEPENDENCIES:
#     random   -- create random numbers in a POSIX safe way

# Not using xargs, because then the expansion would only be evaluated once

while read -r l; do echo "$(random)-$l"; done | sort | sed -E 's/^[0-9]{10}-//'
